### ISSUE TITLE
works fine

### ISSUE THREAD

**Issue by mattneub** [BigDada1/ScreenEdgePanGestureDemo#1]
Your code works fine for me. See video https://youtu.be/HuKnGots5S8

**Comment by BigDada1** [comment]
Which iOS version do you have used in the simulator?

**Comment by BigDada1** [comment]
Ah, now I understand – the Xcode 11 iPhone simulator does not work properly with the gesture. Today I update my iPhone to iOS 13 an … it works fine ☺️
